*
!frontend/
!frontend/**
!frontend-default/
!frontend-default/**
!frontend-admin/
!frontend-admin/**

frontend/node_modules/
frontend/dist/
frontend-default/node_modules/
frontend-default/dist/
frontend-admin/node_modules/
frontend-admin/dist/
