-- Roll back the clean PostgreSQL baseline.
DROP TABLE IF EXISTS public.integration_events CASCADE;
DROP TABLE IF EXISTS public.integration_sync_runs CASCADE;
DROP TABLE IF EXISTS public.external_workers CASCADE;
DROP TABLE IF EXISTS public.external_org_units CASCADE;
DROP TABLE IF EXISTS public.mcp_oauth_tokens CASCADE;
DROP TABLE IF EXISTS public.mcp_oauth_clients CASCADE;
DROP TABLE IF EXISTS public.mcp_tool_approvals CASCADE;
DROP TABLE IF EXISTS public.mcp_services CASCADE;
DROP TABLE IF EXISTS public.user_resource_favorites CASCADE;
DROP TABLE IF EXISTS public.user_kb_pins CASCADE;
DROP TABLE IF EXISTS public.task_dead_letters CASCADE;
DROP TABLE IF EXISTS public.sync_logs CASCADE;
DROP TABLE IF EXISTS public.data_sources CASCADE;
DROP TABLE IF EXISTS public.knowledge_processing_spans CASCADE;
DROP TABLE IF EXISTS public.knowledge_tag_relations CASCADE;
DROP TABLE IF EXISTS public.knowledge_tags CASCADE;
DROP TABLE IF EXISTS public.knowledge_grants CASCADE;
DROP TABLE IF EXISTS public.knowledge_base_grants CASCADE;
DROP TABLE IF EXISTS public.chunks CASCADE;
DROP TABLE IF EXISTS public.knowledges CASCADE;
DROP TABLE IF EXISTS public.knowledge_folders CASCADE;
DROP TABLE IF EXISTS public.knowledge_bases CASCADE;
DROP TABLE IF EXISTS public.vector_stores CASCADE;
DROP TABLE IF EXISTS public.web_search_providers CASCADE;
DROP TABLE IF EXISTS public.messages CASCADE;
DROP TABLE IF EXISTS public.sessions CASCADE;
DROP TABLE IF EXISTS public.custom_agents CASCADE;
DROP TABLE IF EXISTS public.models CASCADE;
DROP TABLE IF EXISTS public.knowledge_domain_admins CASCADE;
DROP TABLE IF EXISTS public.knowledge_domain_storage CASCADE;
DROP TABLE IF EXISTS public.platform_runtime_configs CASCADE;
DROP TABLE IF EXISTS public.knowledge_domains CASCADE;
DROP TABLE IF EXISTS public.user_org_memberships CASCADE;
DROP TABLE IF EXISTS public.org_units CASCADE;
DROP TABLE IF EXISTS public.sso_identities CASCADE;
DROP TABLE IF EXISTS public.auth_tokens CASCADE;
DROP TABLE IF EXISTS public.audit_logs CASCADE;
DROP TABLE IF EXISTS public.system_settings CASCADE;
DROP TABLE IF EXISTS public.users CASCADE;

DROP EXTENSION IF EXISTS pg_trgm;
DROP EXTENSION IF EXISTS "uuid-ossp";
