version: terms-v1
accepted_terms:
  - "3PL"
  - "ADR"
  - "AdvaMed"
  - "AE"
  - "AGM"
  - "AM"
  - "APAC"
  - "APR"
  - "AR"
  - "ASM"
  - "ASP"
  - "ASPM"
  - "ASV"
  - "BA"
  - "BA AL"
  - "BEI"
  - "BGI"
  - "BGI Perf Hub"
  - "BGM"
  - "BoD"
  - "BP"
  - "BPM"
  - "CA"
  - "CAP"
  - "CAPEX"
  - "CC"
  - "CCG"
  - "CCM"
  - "CD"
  - "CDA"
  - "CE"
  - "CE OPS"
  - "CEC"
  - "CEO"
  - "CI"
  - "CIB"
  - "CIRE"
  - "CL"
  - "CLM"
  - "CM"
  - "CML"
  - "CMS"
  - "CNY"
  - "CO"
  - "CoC"
  - "COI"
  - "Concur"
  - "COO"
  - "CoSE"
  - "CPS&MD"
  - "CPT"
  - "CRA"
  - "CRB"
  - "CRM"
  - "CSP"
  - "CST"
  - "CTM"
  - "DAR"
  - "DC"
  - "DD"
  - "DG"
  - "DIA"
  - "DiaDoc"
  - "DIC"
  - "DM"
  - "DMP"
  - "DMS"
  - "DO"
  - "DoA"
  - "DP"
  - "DPS"
  - "DRMA"
  - "DS"
  - "DVS"
  - "ECP"
  - "Event Owner"
  - "Event Specialist"
  - "FA"
  - "FAS"
  - "FEP"
  - "FIN"
  - "FM"
  - "FMV"
  - "FOC"
  - "FP&A"
  - "FSE"
  - "FTE"
  - "GDC"
  - "GL"
  - "GM"
  - "GM-X"
  - "GMM"
  - "GO"
  - "GSD"
  - "HCO"
  - "HCP"
  - "HGR"
  - "HQ"
  - "HW"
  - "IB"
  - "ICF"
  - "ICL"
  - "IHC"
  - "iHCP"
  - "IIT"
  - "ILA"
  - "ILM"
  - "ISA"
  - "IVD"
  - "KPI"
  - "L1 distributor"
  - "L2 Distributor"
  - "LM"
  - "LoA"
  - "LP"
  - "LS"
  - "LT"
  - "MAH"
  - "Mgt./Mgmt"
  - "Mio"
  - "Mkt"
  - "ML"
  - "MOD"
  - "MRA"
  - "MSA"
  - "NPC"
  - "NSD"
  - "ODG"
  - "OSCA"
  - "OSP"
  - "OT"
  - "P&C"
  - "PA"
  - "Partner Agreement"
  - "PL"
  - "PM"
  - "PO"
  - "POBO"
  - "POC"
  - "POD"
  - "PR"
  - "PRI"
  - "PSI"
  - "PSL"
  - "QA"
  - "QMS"
  - "QN"
  - "RA"
  - "RCR"
  - "RCS"
  - "RDSL"
  - "RESC"
  - "RIS China"
  - "RSS"
  - "RTP"
  - "SA"
  - "SA&I"
  - "SaMD"
  - "SCR"
  - "SD"
  - "SFE"
  - "SHE"
  - "SI"
  - "SMD"
  - "SOP"
  - "SPD"
  - "SSC"
  - "SW"
  - "T&E"
  - "TD"
  - "TOM"
  - "TSA"
  - "TSE"
  - "TTD"
  - "VAD"
  - "VBP"
  - "VP"
  - "WTS"
